package blockchain

//The block info structure describes basic information of a block.
type BlockInfo struct {
	// The block hash.
	Hash string
	// The generation hash
	GenerationHash string
	// The sum of all transaction fees included in the block.
	TotalFee uint64
	// The number of transactions included.
	NumTransactions int32
	// The block signature.
	// The signature was generated by the signer and can be used to validate that
	// the blockchain data was not modified by a node.
	Signature string
	// The public account of block harvester.
	Signer string
	// The network type.
	NetworkType int
	// The transaction version.
	Version int
	// The block type.
	Type int
	// The height of which the block was confirmed.
	// Each block has a unique height. Subsequent blocks differ in height by 1.
	Height uint64
	// The number of seconds elapsed since the creation of the nemesis blockchain.
	Timestamp uint64
	// The POI difficulty to harvest a block.
	Difficulty uint64
	// The last block hash.
	PreviousBlockHash string
	// The block transaction hash.
	BlockTransactionsHash string
}
