/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type BlockchainStorageInfoDto struct {

	NumBlocks int32 `json:"numBlocks"`

	NumTransactions int32 `json:"numTransactions"`

	NumAccounts int32 `json:"numAccounts"`
}
