/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type BlockDto struct {

	Signature string `json:"signature"`

	Signer string `json:"signer"`

	Version float32 `json:"version"`

	Type_ float32 `json:"type"`

	Height *UInt64Dto `json:"height"`

	Timestamp *UInt64Dto `json:"timestamp"`

	Difficulty *UInt64Dto `json:"difficulty"`

	PreviousBlockHash string `json:"previousBlockHash"`

	BlockTransactionsHash string `json:"blockTransactionsHash"`
}
