/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type BlockchainScoreDto struct {

	ScoreHigh *UInt64Dto `json:"scoreHigh"`

	ScoreLow *UInt64Dto `json:"scoreLow"`
}
