/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type BlockMetaDto struct {

	Hash string `json:"hash,omitempty"`

	GenerationHash string `json:"generationHash,omitempty"`

	TotalFee *[]UInt64Dto `json:"totalFee,omitempty"`

	MerkleTree []string `json:"-"`

	NumTransactions float32 `json:"numTransactions,omitempty"`
}
