/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type MosaicDefinitionDto struct {

	NamespaceId *UInt64Dto `json:"namespaceId"`

	MosaicId *UInt64Dto `json:"mosaicId"`

	Supply *UInt64Dto `json:"supply"`

	Height *UInt64Dto `json:"height"`

	Owner string `json:"owner"`

	Properties *MosaicPropertiesDto `json:"properties"`

	Levy *interface{} `json:"levy"`
}
