/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type Multisig struct {

	Account string `json:"account"`

	AccountAddress string `json:"accountAddress,omitempty"`

	MinApproval int32 `json:"minApproval"`

	MinRemoval int32 `json:"minRemoval"`

	Cosignatories []string `json:"cosignatories"`

	MultisigAccounts []string `json:"multisigAccounts"`
}
