/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type NamespaceNameDto struct {

	ParentId *UInt64Dto `json:"parentId,omitempty"`

	NamespaceId *UInt64Dto `json:"namespaceId"`

	Name string `json:"name"`
}
