/* 
 * Catapult REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.7.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package infrastructure

type TransactionStatusDto struct {

	Group string `json:"group,omitempty"`

	Status string `json:"status"`

	Hash string `json:"hash,omitempty"`

	Deadline *UInt64Dto `json:"deadline,omitempty"`

	Height *UInt64Dto `json:"height,omitempty"`
}
